m2_tiil_user:
    resource: "@M2TIILUserBundle/Resources/config/routing.yml"
    prefix:   /

m2_tiil_trip_booker:
    resource: "@M2TIILTripBookerBundle/Controller/"
    type: annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
