parameters:
#    m2_tiil_user.example.class: M2TIIL\UserBundle\Example

services:
#    m2_tiil_user.example:
#        class: %m2_tiil_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
