<?php

namespace M2TIIL\TripBookerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConveyanceOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConveyanceOptionRepository extends EntityRepository
{
}
