services:
    sonata.admin.category:
        class: M2TIIL\TripBookerBundle\Admin\TripCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Catégories de voyage" }
        arguments:
            - ~
            - M2TIIL\TripBookerBundle\Entity\TripCategory
            - ~
        calls:
            - [ setTranslationDomain, [M2TIILTripBookerBundle]]
    sonata.admin.trip:
        class: M2TIIL\TripBookerBundle\Admin\TripAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Voyages" }
        arguments:
            - ~
            - M2TIIL\TripBookerBundle\Entity\Trip
            - ~
        calls:
            - [ setTranslationDomain, [M2TIILTripBookerBundle]]
    sonata.admin.conveyance:
        class: M2TIIL\TripBookerBundle\Admin\ConveyanceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Moyens de transport", show_in_dashboard: true }
        arguments:
            - ~
            - M2TIIL\TripBookerBundle\Entity\Conveyance
            - ~
        calls:
            - [ setTranslationDomain, [M2TIILTripBookerBundle]]
    sonata.admin.conveyanceOption:
        class: M2TIIL\TripBookerBundle\Admin\ConveyanceOptionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Options des moyens de transport", show_in_dashboard: true }
        arguments:
            - ~
            - M2TIIL\TripBookerBundle\Entity\ConveyanceOption
            - ~
        calls:
            - [ setTranslationDomain, [M2TIILTripBookerBundle]]