parameters:
#    m2_tiil_trip_booker.example.class: M2TIIL\TripBookerBundle\Example

services:
#    m2_tiil_trip_booker.example:
#        class: %m2_tiil_trip_booker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
